### ISSUE TITLE
[EASY] Fix UltraDV warnings

### ISSUE THREAD

**Issue by Barrett17** [Barrett17/UltraDV#10]
All warnings should be fixed to make the code more clean and stable.

**Comment by vivek-roy** [comment]
Sir, I am working on this.
There are some warnings saying 'unused variable'. Should I keep those variables or remove them?
Thank You

**Comment by Barrett17** [comment]
Hi thanks for being interested in fixing this issue.

Feel free to remove unused variables, but take care with type warnings. It's a non trivial decision, ideally you should always move the original var to the right type and avoid castings. There are some situations where the casting is necessary, in this case the solution should take into account overflows and possible bugs due to this.

**Comment by vivek-roy** [comment]
UltraDV/src/common/AppUtils.cpp: 56: warning: return to 'int32' from 'double'

In the above case (and many similar cases) typecasting is the solution. Even if we don't explicitly typecast the compiler internally does typecast the value, and so explicit typecasting should not bring any new bugs. (Tell me if I am wrong).

Thank You

**Comment by Barrett17** [comment]
Sure, that's OK!

**Comment by vivek-roy** [comment]
I have fixed 90% of the warnings. Remaining 10% needs your attention. If you would clone my changes and help me out with the remaining 10% (https://github.com/vivek-roy/UltraDV). Or should I create a Pull request?

**Comment by Barrett17** [comment]
Submit a pull request it's better that I comment there. Squash commits per kind of fix to avoid messing up the history. I see a lot of "Fixed Typo".

**Comment by Barrett17** [comment]
I mean you can create a main "Fix Warnings" commit.

Some more notes : 

* Don't change NULL with \0
* Please remove unused vars, commenting them increase noise.

**Comment by vivek-roy** [comment]
OK then I'm doing the two changes you mentioned and sending Pull Request. And yes, I planned to squash the commits and so didn't care to properly name the commits. :-P
Thank You

**Comment by vivek-roy** [comment]
Done. Sending Pull Request.

**Comment by Barrett17** [comment]
Fixed:
https://github.com/Barrett17/UltraDV/commit/3427c4240c982ba3e12a07ea068f95c9b06be508
